/**
 * Docker release smoke for projects generated by the latest published
 * `sapporta` CLI package.
 *
 * This is opt-in because it requires npm registry access, a Docker daemon, and
 * a full image build. Run with: pnpm test:e2e:npm:docker
 */
import { afterAll, beforeAll, describe, it } from "vitest";
import {
  assertFrontendRoutes,
  assertProjectHttpApi,
  buildAndRunDockerProject,
  cleanupDockerProject,
  cleanupProject,
  createTempProject,
  rebuildBetterSqlite,
  scaffoldProjectWithNpmCli,
  writeTasksSchema,
  type E2eProject,
  type StartedDockerProject,
} from "./harness.js";

const runNpmDocker =
  process.env.SAPPORTA_E2E_NPM_DOCKER === "1" ? describe : describe.skip;

runNpmDocker("sapporta init from latest npm package - Docker release", () => {
  let project: E2eProject | undefined;
  let dockerProject: StartedDockerProject | undefined;

  beforeAll(async () => {
    project = createTempProject({
      devMode: false,
      prefix: "sapporta-e2e-npm-docker-",
    });

    await scaffoldProjectWithNpmCli(project);
    await rebuildBetterSqlite(project);
    writeTasksSchema(project.projectDir);
    dockerProject = await buildAndRunDockerProject(
      project,
      "sapporta-e2e-npm",
    );
  }, 720_000);

  afterAll(async () => {
    await cleanupDockerProject(project, dockerProject);
    cleanupProject(project);
  });

  it("serves the generated API from the production image", async () => {
    await assertProjectHttpApi(dockerProject!.baseUrl);
  });

  it("serves the generated frontend from the production image", async () => {
    await assertFrontendRoutes(dockerProject!.baseUrl);
  });
});
